[[redirects]]
  force = true
  from = "/scripts/x.js"
  status = 200
  to = "https://armala-payment-api.netlify.app/scripts/x.js"
  [[headers]]
  for = "/*" # you can configure the correct paths here
  [headers.values]
    access-control-allow-origin = "*" # see a list of allowed values here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin